# stages:
#   - build  # Define the 'build' stage
#   - test   # Define the 'test' stage

# before_script:
#   - chmod +x ./script.sh  # Make the 'script.sh' file executable
#   - ./script.sh           # Execute the 'script.sh' script
#   - yarn install          # Install dependencies using Yarn

# test:
#   stage: test                      # Define the 'test' stage job
#   script:
#     - yarn test                   # Run tests using Yarn
#     - yarn lint                   # Perform linting using Yarn
#   only:
#     - merge_requests              # Run only for merge requests
#     - dev                         # Run only for the 'dev' branch
  
# build:
#   stage: build                     # Define the 'build' stage job
#   script:
#     - yarn build                  # Build the project using Yarn
#   only:
#     - merge_requests              # Run only for merge requests
#     - dev                         # Run only for the 'dev' branch
stages:
  - test
  - build
 
before_script:
  - chmod +x ./script.sh
  - ./script.sh
  - yarn install
 
test:
  stage: test
  script:
    - yarn lint
    - yarn test --coverageReporters=text-summary > coverage-summary.txt
    - COVERAGE_CURRENT=$(awk '/Lines/ {print int($3)}' coverage-summary.txt)
    - COVERAGE_PREVIOUS=$(awk '/Lines/ {print int($3)}' /home/coverage/people/coverage-summary-prev.txt)
    - "echo Current Coverage: $COVERAGE_CURRENT"
    - "echo Previous Coverage: $COVERAGE_PREVIOUS"
    - if [ "$COVERAGE_CURRENT" -lt "$COVERAGE_PREVIOUS" ]; then echo "Test coverage decreased!" && exit 1; fi
 
    - sudo mv coverage-summary.txt /home/coverage/people/coverage-summary-prev.txt
  only:
    - merge_requests
    - dev
 
build:
  stage: build
  script:
    - yarn build
  dependencies:
    - test
  only:
    - merge_requests
    - dev
  artifacts:
    paths:
      - $CI_PROJECT_DIR/build